services:
  postgres:
    image: postgres
    container_name: coffee_shop_postgres
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: coffee-shop-api
