services:
  postgres:
    image: ${DBMS_CONTAINER_IMAGE}
    container_name: ${DBMS_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
