services:
  postgres:
    image: ${DBMS_CONTAINER_IMAGE}
    container_name: ${DBMS_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ${CUSTOM_NETWORK}

  app:
    build:
      context: .
      dockerfile: ${BE_APP_CONTAINER_DOCKERFILE}
      args:
        # Inject app env here for App Dockerfile
        NODE_REQUIRED_MAJOR: ${NODE_REQUIRED_MAJOR}
        PORT: ${PORT}
    container_name: ${BE_APP_CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    environment:
      # Inject app env here for App codebase
      API_PREFIX: "${API_PREFIX}"
      DATABASE_URL: "${DBMS_CONTAINER_URL}"
      PORT: "${PORT}"
      NODE_ENV: "${NODE_ENV}"
    depends_on:
      - ${DBMS_CONTAINER_IMAGE}
    networks:
      - ${CUSTOM_NETWORK}

networks:
  coffee_shop_net:
    name: ${CUSTOM_NETWORK_NAME}
